# Project
## Business Understanding
This project looks at a dataset about student achievement in secondary education. The attributes include grades, demographic, social and school related features. The purpose of this project is to predict whether students will get a passing grade and to find out which features affect grades the most. This can help schools decide what to use their resources on and to target students who might need additional resources based on these features. This project focuses on finding out how well you can predict student performance with information any school or school district should have easy access to.

#### Research questions
- Can you predict passing grades with the whole dataset
- Can you do it while limiting the data to features the school should have readily available
- Which features affect students passing the most

## Data Understanding
For this project the dataset from [https://archive.ics.uci.edu/dataset/320/student+performance](https://archive.ics.uci.edu/dataset/320/student+performance) is used which contains a dataset with 649 instances with 30 features. There are no missing values in the dataset.  
2 diffent versions of the model will be built. One that only includes variables that a school should already have in their system or be otherwise readily available. The second model will use more features and will be used to compare to and evaluate the accuracy of the primary model.
#### Features in both Models
sex - student's sex (binary: 'M' / 'F')  
age - student's age (integer: between 15 to 22)  
address - students home address type (binary: 'R' rural / 'U' urban)  
famsize - family size (binary: 'LE3' less or equal to 3 / 'GE3' greater than 3)  
Pstatus - parent's cohabitation status (binary: 'T' together / 'A' apart)  
guardian - student's guardian (nominal: 'mother', 'father' or 'other)  
traveltime - home to school travel time (numeric: 1 = <15 min, 2 = 15 to 30 min, 3 = 30 to 60 min, 4 = >60 min)  
failures - number of past class failures (numeric: 1 to 4, 4 if over 4)  
schoolsup - extra educational support (binary: 'yes' or 'no')  
paid - extra paid classes for the subject (binary: 'yes' or 'no')  
nursery - attended nursery school (binary: 'yes' or 'no')  
absences - number of school absences (numeric: from 0 to 93)  

#### Features added to Secondary model
Medu/Fedu - mother's/father's education (njumeric: 0 = none, 1 = 4th grade, 2 = 5th to 9th grade, 3 = secondary education, 4 = higher education)  
reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')  
famsup - family educational support (binary: 'yes' or 'no')  
studytime - weekly study time (numeric: 1 = <2 hours, 2= 2 to 5 hours, 3 = 5 to 10 hours, 4 = >10 hours)  
activities - extra-curricular activities (binary: 'yes' or 'no')  
higher - wants to take higher education (binary: 'yes' or 'no')  
internet - internet access at home (binary: 'yes' or 'no')  
romantic - in a romantic relationship (binary: 'yes' or 'no')  
famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)  
freetime - free time after school (numeric: from 1 - very low to 5 - very high)  
goout - going out with friends (numeric: from 1 - very low to 5 - very high)  
Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)  
Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)  
health - current health status (numeric: from 1 - very bad to 5 - very good)  
  
#### Excluded Features
school - student's school. Irrelevant to a generalizable model  
Mjob/Fjob - mother's/father's job. The categorization is hazy and mostly of value 'other'  
G1 and G2 - first and second period grades. These values are too highly related to the final grade and would make the models worse.

## Data Preparation

In [34]:
from ucimlrepo import fetch_ucirepo   
# fetch dataset 
student_performance = fetch_ucirepo(id=320) 
# data (as pandas dataframes) 
X = student_performance.data.features 
y = student_performance.data.targets 
  
# metadata 
#print(student_performance.metadata) 
  
# variable information 
print(student_performance.variables)

          name     role         type      demographic  \
0       school  Feature  Categorical             None
1          sex  Feature       Binary              Sex
2          age  Feature      Integer              Age
3      address  Feature  Categorical             None
4      famsize  Feature  Categorical            Other
5      Pstatus  Feature  Categorical            Other
6         Medu  Feature      Integer  Education Level
7         Fedu  Feature      Integer  Education Level
8         Mjob  Feature  Categorical       Occupation
9         Fjob  Feature  Categorical       Occupation
10      reason  Feature  Categorical             None
11    guardian  Feature  Categorical             None
12  traveltime  Feature      Integer             None
13   studytime  Feature      Integer             None
14    failures  Feature      Integer             None
15   schoolsup  Feature       Binary             None
16      famsup  Feature       Binary             None
17        paid  Feature       Binary             None
18  activities  Feature       Binary             None
19     nursery  Feature       Binary             None
20      higher  Feature       Binary             None
21    internet  Feature       Binary             None
22    romantic  Feature       Binary             None
23      famrel  Feature      Integer             None
24    freetime  Feature      Integer             None
25       goout  Feature      Integer             None
26        Dalc  Feature      Integer             None
27        Walc  Feature      Integer             None
28      health  Feature      Integer             None
29    absences  Feature      Integer             None
30          G1   Target  Categorical             None
31          G2   Target  Categorical             None
32          G3   Target      Integer             None

                                          description units missing_values
0   student's school (binary: 'GP' - Gabriel Perei...  None             no
1   student's sex (binary: 'F' - female or 'M' - m...  None             no
2              student's age (numeric: from 15 to 22)  None             no
3   student's home address type (binary: 'U' - urb...  None             no
4   family size (binary: 'LE3' - less or equal to ...  None             no
5   parent's cohabitation status (binary: 'T' - li...  None             no
6   mother's education (numeric: 0 - none,  1 - pr...  None             no
7   father's education (numeric: 0 - none,  1 - pr...  None             no
8   mother's job (nominal: 'teacher', 'health' car...  None             no
9   father's job (nominal: 'teacher', 'health' car...  None             no
10  reason to choose this school (nominal: close t...  None             no
11  student's guardian (nominal: 'mother', 'father...  None             no
12  home to school travel time (numeric: 1 - <15 m...  None             no
13  weekly study time (numeric: 1 - <2 hours, 2 - ...  None             no
14  number of past class failures (numeric: n if 1...  None             no
15      extra educational support (binary: yes or no)  None             no
16     family educational support (binary: yes or no)  None             no
17  extra paid classes within the course subject (...  None             no
18    extra-curricular activities (binary: yes or no)  None             no
19        attended nursery school (binary: yes or no)  None             no
20  wants to take higher education (binary: yes or...  None             no
21        Internet access at home (binary: yes or no)  None             no
22   with a romantic relationship (binary: yes or no)  None             no
23  quality of family relationships (numeric: from...  None             no
24  free time after school (numeric: from 1 - very...  None             no
25  going out with friends (numeric: from 1 - very...  None             no
26  workday alcohol consumption (numeric: from 1 -...  None             no
27  weekend alcohol consumption (numeric: from 1 -...  None             no
28  current health status (numeric: from 1 - very ...  None             no
29  number of school absences (numeric: from 0 to 93)  None             no
30         first period grade (numeric: from 0 to 20)  None             no
31        second period grade (numeric: from 0 to 20)  None             no
32  final grade (numeric: from 0 to 20, output tar...  None             no

In [14]:
X.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,2
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,6
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,0
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,yes,no,5,4,2,1,2,5,6
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,yes,no,4,4,4,1,1,3,0
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,yes,no,no,4,1,4,1,1,1,2
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,yes,no,4,2,2,1,1,1,0
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,yes,no,5,5,1,1,1,5,0

In [96]:
import pandas as pd
from ucimlrepo import fetch_ucirepo   
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# fetch dataset 
student_performance = fetch_ucirepo(id=320) 
# data (as pandas dataframes) 
X = student_performance.data.features 
y = student_performance.data.targets 

# drop unnecessary values from targets and transform target to binary
y = y.drop(columns = ['G1', 'G2'])
y_binary = (y >= 10).astype(int).values.ravel()

X = X.drop(columns = ['school', 'reason','Mjob', 'Fjob'])


# convert binaries to numerical values
X['sex'] = pd.get_dummies(X['sex'], dtype='int64')['F']
X['famsize'] = pd.get_dummies(X['famsize'], dtype='int64')['GT3']
X['Pstatus'] = pd.get_dummies(X['Pstatus'], dtype='int64')['T']
X['address'] = pd.get_dummies(X['address'], dtype='int64')['U']
X['schoolsup'] = pd.get_dummies(X['schoolsup'], dtype='int64')['yes']
X['famsup'] = pd.get_dummies(X['famsup'], dtype='int64')['yes']
X['paid'] = pd.get_dummies(X['paid'], dtype='int64')['yes']
X['activities'] = pd.get_dummies(X['activities'], dtype='int64')['yes']
X['nursery'] = pd.get_dummies(X['nursery'], dtype='int64')['yes']
X['higher'] = pd.get_dummies(X['higher'], dtype='int64')['yes']
X['internet'] = pd.get_dummies(X['internet'], dtype='int64')['yes']
X['romantic'] = pd.get_dummies(X['romantic'], dtype='int64')['yes']
X = pd.get_dummies(X, columns=['guardian'], dtype='int64', drop_first=True) 

# rename binaries by which one is 1
X.rename(columns={'sex' : 'sex_f', 'famsize':'famsize_GT3', 'Pstatus':'Pstatus_T', 'address':'address_U',}, inplace = True)

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X_train.columns)

X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.3, random_state=512)

# Scale the training data since it's essential for the logistic regression and doesn't hurt the random forest model



X_secondary_train = X_train
X_primary_train = X_train.drop(columns = ['Medu','Fedu','famsup','studytime','activities','higher','internet','romantic','famrel','freetime','goout','Dalc','Walc','health'])
X_secondary_test = X_test
X_primary_test = X_test.drop(columns = ['Medu','Fedu','famsup','studytime','activities','higher','internet','romantic','famrel','freetime','goout','Dalc','Walc','health'])

In [82]:

X_primary_train.head()

,sex_f,age,address_U,famsize_GT3,Pstatus_T,traveltime,failures,schoolsup,paid,nursery,absences,guardian_mother,guardian_other
0,-1.162898,1.043155,-1.513227,0.630018,0.378915,-0.765228,-0.364165,-0.297874,-0.241402,0.524672,0.074832,0.660840,-0.261219
1,0.859921,-0.592743,-1.513227,0.630018,0.378915,0.540838,-0.364165,-0.297874,-0.241402,0.524672,-0.843376,0.660840,-0.261219
2,-1.162898,-0.592743,-1.513227,0.630018,0.378915,0.540838,-0.364165,-0.297874,-0.241402,-1.905952,-0.384272,0.660840,-0.261219
3,-1.162898,1.043155,0.660840,0.630018,0.378915,-0.765228,-0.364165,-0.297874,-0.241402,0.524672,0.074832,-1.513227,-0.261219
4,0.859921,-0.592743,-1.513227,0.630018,0.378915,0.540838,-0.364165,-0.297874,-0.241402,-1.905952,0.533936,0.660840,-0.261219

In [97]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report

forest_model_secondary = RandomForestClassifier(n_estimators=100, bootstrap=True, max_samples=0.7, max_features=0.6, random_state=512)
forest_model_primary = RandomForestClassifier(n_estimators=100, bootstrap=True, max_samples=0.7, max_features=0.6, random_state=512)
forest_model_primary.fit(X_primary_train, y_train)
forest_model_secondary.fit(X_secondary_train, y_train)




y_pred = forest_model_primary.predict(X_primary_test)
print('Primary')
print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred)}')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
print (forest_model_primary.feature_importances_)
feat_importances = pd.Series(forest_model_primary.feature_importances_, index=X_primary_train.columns)
print(feat_importances.sort_values(ascending=False))

print('Secondary')
y_pred_secondary = forest_model_secondary.predict(X_secondary_test)
print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred_secondary)}')

print(classification_report(y_test, y_pred_secondary))
print (forest_model_secondary.feature_importances_)


feat_importances = pd.Series(forest_model_secondary.feature_importances_, index=X_secondary_train.columns)
print(feat_importances.sort_values(ascending=False))

Primary
Confusion matrix:
[[ 14  20]
 [ 14 147]]
              precision    recall  f1-score   support

           0       0.50      0.41      0.45        34
           1       0.88      0.91      0.90       161

    accuracy                           0.83       195
   macro avg       0.69      0.66      0.67       195
weighted avg       0.81      0.83      0.82       195

[0.06907922 0.1506754  0.05121255 0.06537459 0.02436615 0.10017073
 0.1665874  0.02642176 0.02037088 0.05002216 0.21453558 0.04220773
 0.01897585]
absences           0.214536
failures           0.166587
age                0.150675
traveltime         0.100171
sex_f              0.069079
famsize_GT3        0.065375
address_U          0.051213
nursery            0.050022
guardian_mother    0.042208
schoolsup          0.026422
Pstatus_T          0.024366
paid               0.020371
guardian_other     0.018976
dtype: float64
Secondary
Confusion matrix:
[[ 12  22]
 [  8 153]]
              precision    recall  f1-score   support

           0       0.60      0.35      0.44        34
           1       0.87      0.95      0.91       161

    accuracy                           0.85       195
   macro avg       0.74      0.65      0.68       195
weighted avg       0.83      0.85      0.83       195

[0.01603199 0.04527546 0.03172597 0.01944856 0.00913437 0.04169094
 0.04647549 0.03338613 0.02765016 0.1283129  0.00753011 0.01169185
 0.01641064 0.02440185 0.0214112  0.08078513 0.01691424 0.02016202
 0.06993681 0.04598835 0.06875479 0.03814083 0.03947113 0.0360425
 0.08444345 0.01295731 0.00582579]
failures           0.128313
absences           0.084443
higher             0.080785
famrel             0.069937
goout              0.068755
Fedu               0.046475
freetime           0.045988
age                0.045275
Medu               0.041691
Walc               0.039471
Dalc               0.038141
health             0.036042
traveltime         0.033386
address_U          0.031726
studytime          0.027650
activities         0.024402
nursery            0.021411
romantic           0.020162
famsize_GT3        0.019449
internet           0.016914
paid               0.016411
sex_f              0.016032
guardian_mother    0.012957
famsup             0.011692
Pstatus_T          0.009134
schoolsup          0.007530
guardian_other     0.005826
dtype: float64

In [100]:
from sklearn.linear_model import LogisticRegression
#Primary model
reg_primary = LogisticRegression(solver='lbfgs', max_iter=1000)
reg_primary.fit(X_primary_train,y_train)

print("Coefficients: ",reg_primary.coef_)
print("Intercept: ", reg_primary.intercept_)

y_pred = reg_primary.predict(X_primary_test)

print('Primary')
print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred)}')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


feat_importances = pd.Series(reg_primary.coef_.ravel(), index=X_primary_train.columns)
print(feat_importances.sort_values(ascending=False))

#Secondary model
reg_secondary = LogisticRegression(solver='lbfgs', max_iter=1000)
reg_secondary.fit(X_secondary_train,y_train)

print("Coefficients: ",reg_secondary.coef_)
print("Intercept: ", reg_secondary.intercept_)

y_pred_secondary = reg_secondary.predict(X_secondary_test)

print('Primary')
print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred_secondary)}')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_secondary))


feat_importances = pd.Series(reg_secondary.coef_.ravel(), index=X_secondary_train.columns)
print(feat_importances.sort_values(ascending=False))

Coefficients:  [[ 0.06062786 -0.19289333  0.34263807 -0.08792953  0.11882454 -0.02278558
  -0.64157247  0.33598855 -0.02443552 -0.12597687 -0.09559625 -0.10473681
   0.17367275]]
Intercept:  [2.02540671]
Primary
Confusion matrix:
[[  6  28]
 [  0 161]]
              precision    recall  f1-score   support

           0       1.00      0.18      0.30        34
           1       0.85      1.00      0.92       161

    accuracy                           0.86       195
   macro avg       0.93      0.59      0.61       195
weighted avg       0.88      0.86      0.81       195

address_U          0.342638
schoolsup          0.335989
guardian_other     0.173673
Pstatus_T          0.118825
sex_f              0.060628
traveltime        -0.022786
paid              -0.024436
famsize_GT3       -0.087930
absences          -0.095596
guardian_mother   -0.104737
nursery           -0.125977
age               -0.192893
failures          -0.641572
dtype: float64
Coefficients:  [[ 0.03427712 -0.0530401   0.30695369 -0.10373384  0.13131257  0.09116769
   0.09042587 -0.00461685  0.19997863 -0.48373333  0.28577179 -0.05352576
  -0.10230484  0.27910098 -0.17013769  0.36730496  0.12827417 -0.20201892
   0.01109322 -0.20815082 -0.0186716  -0.08957583 -0.04266779 -0.07257915
  -0.07905405 -0.18228471  0.17624293]]
Intercept:  [2.21057037]
Primary
Confusion matrix:
[[ 10  24]
 [  4 157]]
              precision    recall  f1-score   support

           0       0.71      0.29      0.42        34
           1       0.87      0.98      0.92       161

    accuracy                           0.86       195
   macro avg       0.79      0.63      0.67       195
weighted avg       0.84      0.86      0.83       195

higher             0.367305
address_U          0.306954
schoolsup          0.285772
activities         0.279101
studytime          0.199979
guardian_other     0.176243
Pstatus_T          0.131313
internet           0.128274
Medu               0.091168
Fedu               0.090426
sex_f              0.034277
famrel             0.011093
traveltime        -0.004617
goout             -0.018672
Walc              -0.042668
age               -0.053040
famsup            -0.053526
health            -0.072579
absences          -0.079054
Dalc              -0.089576
paid              -0.102305
famsize_GT3       -0.103734
nursery           -0.170138
guardian_mother   -0.182285
romantic          -0.202019
freetime          -0.208151
failures          -0.483733
dtype: float64